version: '3.8'

services:
  aeroassist-web:
    build: .
    container_name: aeroassist_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-aeroassist_prod_jwt_sec_984f7a2b901e47c182}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY:-aeroassist_admin_key_77312984ef01a}
      - FLASK_ENV=production
      - USE_SQLITE_TEST=0
