-- =========================================================
-- AeroAssist AI – Supabase Cloud Database Schema Setup
-- Run this SQL script in your Supabase SQL Editor (Database -> SQL Editor)
-- =========================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    password TEXT,
    mobile TEXT,
    profile_photo TEXT,
    nationality TEXT,
    preferred_language TEXT DEFAULT 'en',
    account_type TEXT DEFAULT 'Passenger',
    security_preferences TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. FLIGHT BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.flight_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    booking_id TEXT,
    pnr TEXT,
    payment_id TEXT,
    transaction_id TEXT,
    ticket_number TEXT,
    invoice_number TEXT,
    origin TEXT,
    destination TEXT,
    departure_date TEXT,
    flight_details JSONB,
    passenger_details JSONB,
    amount NUMERIC DEFAULT 0,
    payment_method TEXT DEFAULT 'UPI',
    payment_status TEXT DEFAULT 'Demo Success',
    booking_status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PARKING BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.parking_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id TEXT,
    user_email TEXT NOT NULL,
    zone TEXT NOT NULL,
    slot_number TEXT,
    terminal TEXT DEFAULT 'Terminal 1',
    duration_hours INT DEFAULT 2,
    entry_time TEXT,
    exit_time TEXT,
    hours INT NOT NULL,
    plate_number TEXT NOT NULL,
    payment_method TEXT NOT NULL,
    total_price NUMERIC NOT NULL,
    status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. FOOD & RETAIL ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    vendor_id INT,
    terminal TEXT,
    gate TEXT,
    total_price NUMERIC NOT NULL,
    payment_method TEXT DEFAULT 'COD',
    payment_status TEXT DEFAULT 'Completed',
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id INT,
    product_name TEXT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL
);

-- 6. LOUNGE BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.lounge_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    vendor_id INT,
    booking_date TEXT NOT NULL,
    booking_time TEXT NOT NULL,
    slots INT NOT NULL DEFAULT 1,
    status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. LOST AND FOUND ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.lost_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'General',
    type TEXT NOT NULL DEFAULT 'lost',
    location TEXT,
    date TEXT,
    contact_email TEXT NOT NULL,
    reporter_name TEXT,
    status TEXT DEFAULT 'Open',
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. VENDORS TABLE
CREATE TABLE IF NOT EXISTS public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'restaurant',
    terminal TEXT,
    gate TEXT,
    rating NUMERIC DEFAULT 4.5,
    image_url TEXT,
    availability TEXT DEFAULT 'Available'
);

-- 9. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    rating NUMERIC DEFAULT 4.5,
    image_url TEXT,
    category TEXT,
    description TEXT,
    is_available BOOLEAN DEFAULT TRUE
);

-- 10. LOGIN HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    client_type TEXT DEFAULT 'App',
    ip_address TEXT,
    login_time TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security (RLS) or add public access policies so backend API key can insert/select seamlessly
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.flight_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.parking_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.lounge_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.lost_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_history DISABLE ROW LEVEL SECURITY;
